[project]
name = "oralLesionNet"
version = "2.2.0"
description = "Oral Lesion Segmentation Deep Learning Network."
dependencies = [
    "tensorflow",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"