[project]
name = "aidoc"
version = "1.0.0"
description = "Artificial Intelligent system for Detecting and analyzing pmds and Oral Cancer (AIDOC)."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"