CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL,
  `surname` varchar(255) DEFAULT NULL,
  `national_id` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `job` varchar(255) DEFAULT NULL,
  `hospital` varchar(255) DEFAULT NULL,
  `province` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `license` varchar(255) DEFAULT NULL,
  `is_patient` boolean DEFAULT FALSE,
  `is_osm` boolean DEFAULT FALSE,
  `is_specialist` boolean DEFAULT FALSE,
  `is_admin` boolean DEFAULT FALSE,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `submission_records` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `fname` varchar(255) NOT NULL,
  `sender_id` int DEFAULT NULL,
  `sender_phone` varchar(255) DEFAULT NULL,
  `special_request` tinyint NOT NULL DEFAULT 0,
  `zip_code` varchar(255) DEFAULT NULL,
  `patient_id` varchar(255) DEFAULT NULL,
  `general_comment` varchar(255) NOT NULL DEFAULT '',
  `dentist_id` int DEFAULT NULL,
  `dentist_feedback_code` varchar(255) DEFAULT NULL,
  `dentist_feedback_comment` varchar(255) NOT NULL DEFAULT '',
  `dentist_feedback_lesion` tinyint DEFAULT NULL,
  `dentist_feedback_location` tinyint DEFAULT NULL,
  `dentist_feedback_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `biopsy_fname` varchar(255) DEFAULT NULL,
  `biopsy_comment` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `longitude` varchar(255) DEFAULT NULL,
  `latitude` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;